name: Ejercicio workflow


on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - name: Step 1
        run: echo step1  
      
      - name: Step 2
        run: echo step2  

  job2:
    needs: job1
    runs-on: ubuntu-latest  
    steps:
      - name: Cowsay Action
        uses: mscoutermarsh/cowsays-action@master  
        with:
          mesage: "Hola de nuevo desde GitHub Actions!"  
          