name: Example Workflow

# Define el evento workflow_dispatch para ejecutar el flujo de trabajo manualmente.
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest  # Define el entorno en el que se ejecutar치n los trabajos (ubuntu-latest en este caso).
    steps:
      - name: Step 1
        run: echo step1  # Primer paso: Ejecuta el comando echo para mostrar 'step1'.
      
      - name: Step 2
        run: echo step2  # Segundo paso: Ejecuta el comando echo para mostrar 'step2'.

  job2:
    needs: job1  # Define que job2 depende de job1.
    runs-on: ubuntu-latest  # Define el entorno en el que se ejecutar치 job2 (ubuntu-latest en este caso).
    steps:
      - name: Cowsay Action
        uses: mscoutermarsh/cowsays-action@master  # Especifica la acci칩n de Cowsay desde el Marketplace de GitHub.
        with:
          message: "Hello from GitHub Actions!"  # Mensaje que se mostrar치 en arte ASCII de vaca.